package Cineastic::Model::Cineastic;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Cineastic::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:cineastic',
        user => 'cineastic',
        password => 'xcineasticx',
    }
);

=head1 NAME

Cineastic::Model::Cineastic - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Cineastic>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Cineastic::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

David Hodgkinson

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
